#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/bootstrap/app.php';
require __DIR__ . '/Framework/commands/MigrateCommand.php';

use Symfony\Component\Console\Application;

// cli versions
$app = new Application('MoFramework', '1.0.0');

// Register commands
$app->addCommand(new MigrateCommand());

$app->run();